### ISSUE TITLE
Feature: add pagination system to classement command

### ISSUE THREAD

**Issue by WeeskyBDW** [Riksou/WorkMC#1]
What's the problems ?
Actually, we can just see the top ten of members in terms of experience

What's your suggestion  ?
I think it can be nice to make a pagination system when we do `!classement 2`, it show the second page etc... 

Alternative feature 
Instead of a pagination system, add the possibility to show member level (and his XP) and also his global level with a ping argument. Exemple: `!classement @WeeskyBDW#6172`

**Comment by Riksou** [comment]
Closing this issue since it is not related to the same discord bot.
